dispatcher:
  concurrent_requests: 4
  chunk_size: 5242880 # 5 MB
  bucket_name: osm-data

osm:
  base_url: https://download.geofabrik.de
  regions:
    - montenegro
    - malta
    - macedonia
    - france/guyane

storage:
  base_url: ${STORAGE_BASE_URL}
  region: ${STORAGE_REGION}
  username: ${STORAGE_USERNAME}
  password: ${STORAGE_PASSWORD}
