include:
  - services/osm-dispatcher/compose.yml
  - services/osm-storage/compose.yml

services:
  api-gateway:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock