# config.yaml (root level)
app:
  name: haydov
  environment: local  # local, development, staging, production
  log_level: debug

# Service discovery / URLs
services:
  storage:
    base_url: localhost:9000
    region: us-east-1
    username: admin
    password: minio_password
  
  message_broker:
    url: amqp://guest:guest@localhost:5672/
    management_url: http://localhost:15672
  
  database:
    url: postgresql://localhost:5432/haydov
    username: postgres
    password: postgres

# Individual service configs
downloader:
  concurrent_requests: 4
  chunk_size: 5242880  # 5 MB
  bucket_name: osm-data
  retry_attempts: 3
  timeout_seconds: 30

uploader:
  batch_size: 100
  compression: gzip

# Development specific
dev:
  data_dir: .dev
  hot_reload: true
  mock_external_apis: false