version: "3"

services:

  auth:
    build:
      args:
        NODE_ENV: ${NODE_ENV}

  auth-db:
    environment:
      POSTGRES_PASSWORD: admin

  api-db:
    environment:
      POSTGRES_PASSWORD: admin

  kratos-db:
    environment:
      POSTGRES_PASSWORD: admin