version: "3"

services:

  auth-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: hydra
      POSTGRES_USER: hydra
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    
  kratos-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: kratos
      POSTGRES_USER: kratos
    volumes:
      - kratos_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - intranet

  api-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
    volumes:
      - api_db_data:/var/lib/postgresql/data

  auth:
    image: oryd/hydra:v2.2.0
    depends_on:
      - auth-db
    environment:
      DSN: postgres://hydra:admin@auth-db:5432/hydra?sslmode=disable

  kratos-migrate:
    image: oryd/kratos:v0.13.0
    depends_on:
      kratos-db: 
        condition: service_healthy
    environment:
      - DSN=postgres://kratos:admin@kratos-db:5432/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:admin@kratos-db:5432/kratos?sslmode=disable
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
  
  accounts:
    build: 
      context: .
      dockerfile: ./accounts/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:3000
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - intranet
    restart: on-failure

  api:
    image: hasura/graphql-engine:v2.28.1
    ports:
    - ${HAYDOV_API_PORT}:8080
    depends_on:
    - api-db
    - auth
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://api:admin@api-db:5432/api
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_JWT_SECRET: "{\"jwk_url\": \"${HAYDOV_API_JWKS_URI}\"}"

volumes:
  auth_db_data:
  api_db_data:
  kratos_db_data:

networks:
  intranet: