apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: haydov

build:
  artifacts:
    - image: geography-dispatcher
      context: services/geography/dispatcher
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'services/geography/dispatcher/src/**'
            dest: '/app/src'
    - image: geography-storage
      context: services/geography/storage
      docker:
        dockerfile: Dockerfile

portForward:
  - resourceType: service
    resourceName: message-broker
    port: 15672
    localPort: 15672

manifests:
  kustomize:
    paths:
      - services/message-broker
      - services/geography
      - services/geography/storage/base
      - services/geography/dispatcher/base
  rawYaml:
    - services/geography/storage/base/deployment.yaml
    - services/geography/storage/base/service.yaml
    - services/geography/dispatcher/base/deployment.yaml
    - services/geography/dispatcher/base/service.yaml
  helm:
    releases:
      - name: message-broker
        remoteChart: rabbitmq
        version: 16.0.10
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - services/message-broker/values.yaml
        upgradeOnChange: true