apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: haydov
build:
  artifacts:
    - image: geography-dispatcher
      context: services/geography/dispatcher
      docker:
        dockerfile: Dockerfile
        target: development
manifests:
  kustomize:
    paths:
      - services/geography/dispatcher/overlays/dev
  rawYaml:
    - services/geography/dispatcher/deployment.yaml
    - services/geography/dispatcher/service.yaml
    - services/message-broker/deployment.yaml
    - services/message-broker/service.yaml