apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: haydov

build:
  local:
    push: false
    useBuildkit: true
    useDockerCLI: true

  artifacts:
    - image: pnpm-root
      context: .
      docker:
        dockerfile: Dockerfile
        target: pnpm-root

    - image: cargo-root
      context: .
      docker:
        dockerfile: Dockerfile
        target: cargo-root

    - image: geography-dispatcher
      context: services/geography/dispatcher
      requires:
        - image: "cargo-root"
          alias: "workspace_root"
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: "services/geography/dispatcher/src/**"
            dest: "/app/src"

    - image: geography-importer
      context: services/geography/importer
      requires:
        - image: "pnpm-root"
          alias: "workspace_root"
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: "services/geography/importer/src/**"
            dest: "/app/src"

portForward:
  - resourceType: service
    resourceName: message-broker
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: geography-storage-console
    port: 9090
    localPort: 9090

manifests:
  kustomize:
    paths:
      - services/geography
      - services/geography/storage
      - services/message-broker
  rawYaml:
    - services/geography/dispatcher/deployment.yaml
    - services/geography/dispatcher/service.yaml
    - services/geography/importer/deployment.yaml
    - services/geography/importer/service.yaml
  helm:
    releases:
      - name: message-broker
        remoteChart: rabbitmq
        version: 16.0.10
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - services/message-broker/helm/values.yaml
        upgradeOnChange: true

      - name: geography-storage
        remoteChart: minio
        version: 17.0.12
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - services/geography/storage/helm/values.yaml
        upgradeOnChange: true
