apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: haydov

build:
  local:
    push: false
    useBuildkit: true
    useDockerCLI: true

  artifacts:
    - image: geography-dispatcher
      context: services/geography/dispatcher
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'services/geography/dispatcher/src/**'
            dest: '/app/src'

portForward:
  - resourceType: service
    resourceName: message-broker
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: geography-storage-console
    port: 9090
    localPort: 9090

manifests:
  kustomize:
    paths:
      - services/message-broker
      - services/geography/storage
      - services/geography/dispatcher
  rawYaml:
    - services/geography/storage/configmap.yaml
    - services/geography/dispatcher/service.yaml
  helm:
    releases:
      - name: message-broker
        remoteChart: rabbitmq
        version: 16.0.10
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - services/message-broker/helm/values.yaml
        upgradeOnChange: true

      - name: geography-storage
        remoteChart: minio
        version: 17.0.12
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - services/geography/storage/helm/values.yaml
        upgradeOnChange: true