downloader:
  concurrent_requests: 4
  chunk_size: 5242880 # 5 MB
  bucket_name: osm-data

provider: 
  component: ./examples/data-provider/target/wasm32-wasip2/debug/data_provider.wasm
  schema: 
    base_url: https://data.provider/maps
    filename_template: "{region}-latest.osm.pbf"
    regions:
      - europe/montenegro
      - europe/malta
      - asia/japan
  
storage:
  base_url: localhost:9000
  region: us-east-1
  username: minio
  password: minio123
