apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-dispatcher
  template:
    metadata:
      labels:
        app: geography-dispatcher
    spec:
      containers:
        - name: geography-dispatcher
          image: geography-dispatcher:latest
          envFrom:
            - configMapRef:
                name: geography-dispatcher-config
            - configMapRef:
                name: geography-config
            - secretRef:
                name: geography-credentials
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
