[package]
name = "maps-dispatcher"
version = "0.1.0"
edition = "2024"

[dependencies]
maps-utils = { path = "../utils" }
async-trait = "0.1.88"
aws-sdk-s3 = "1.100.0"
bytes = "1.10.1"
futures = "0.3.31"
thiserror = "2.0.12"
url = { version = "2.5.4", features = ["serde"] }
reqwest = {version = "0.12.22", features = ["stream"] }
anyhow = "1.0.98"
aws-config = "1.8.3"
config = "0.15.13"
tokio = { version = "1.47.0", features = ["full"] }
serde = "1.0.219"
rhai = { version = "1.22.2", features = ["serde"] }
serde_json = "1.0.141"
