#!/bin/bash

set -euxo pipefail

export MINIO_NOTIFY_AMQP_URL_PRIMARY="$MESSAGE_BROKER_SCHEMA://$MESSAGE_BROKER_USERNAME:$MESSAGE_BROKER_PASSWORD@$MESSAGE_BROKER_HOST:$MESSAGE_BROKER_PORT"
export MINIO_NOTIFY_AMQP_ENABLE_PRIMARY=on

exec minio server \
    --address "${MINIO_ADDRESS:-:9000}" \
    --console-address "${MINIO_CONSOLE_ADDRESS:-:9001}" \
    "$MINIO_DATA_PATH"