#!/bin/bash

export MINIO_NOTIFY_AMQP_URL_PRIMARY="$MESSAGE_BROKER_SCHEMA://$MESSAGE_BROKER_USERNAME:$MESSAGE_BROKER_PASSWORD@$MESSAGE_BROKER_HOST:$MESSAGE_BROKER_PORT"
minio server /bitnami/minio/data