services:
  osm-dispatcher:
    build:
      context: ./
      target: development
    env_file: .env
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
    ports:
      - 3000:3000