configMapGenerator:
  - name: geography-storage-scripts
    files:
      - ./scripts/configure.sh
      - ./scripts/start.sh
  - name: geography-storage-config
    envs:
      - .env
secretGenerator:
  - name: geography-storage-credentials
    envs:
      - .env.secret
generatorOptions:
  disableNameSuffixHash: true
