bucket_name: osm-data
component: ../../target/wasm32-wasip2/debug/osm_provider.wasm
schema:
  base_url: https://download.geofabrik.de
  filename_template: "{region}-latest.osm.pbf"
  regions:
    - europe/montenegro
    - europe/malta
    - europe/macedonia
    - europe/france/guyane