services:
  osm-storage:
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-haydov_access}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-haydov_secret}
    labels:
      - "traefik.http.routers.haydov.rule=Host(`geography.haydov.localhost`)"