dispatcher:
  concurrent_requests: 4
  chunk_size: 5242880 # 5 MB
  bucket_name: osm-data

schema:
  base_url: https://download.geofabrik.de
  filename_template: "{region}-latest.osm.pbf"
  regions:
    - europe/montenegro
    - europe/malta
    - europe/macedonia
    - europe/france/guyane
    - north-america/united-states/california

component: ./examples/geofabrik-plugin/target/wasm32-wasip2/debug/geofabrik_plugin.wasm

storage:
  base_url: localhost:9000
  region: us-east-1
  username: minio
  password: minio123
