services:
  geocoding-importer:
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    depends_on:
      message:
        condition: service_healthy

  # maps-geocoder:
  #   image: pelias/api:master
  #   user: "${DOCKER_USER}"
  #   restart: always
  #   environment: ["PORT=4000"]
  #   ports: ["0.0.0.0:4000:4000"]
  #   volumes:
  #     - "./pelias.json:/code/pelias.json"
  #   depends_on:
  #     - maps-placeholder
      
  # maps-schema:
  #   image: pelias/schema:master
  #   user: "${DOCKER_USER}"
  #   volumes:
  #     - "./pelias.json:/code/pelias.json"

  # maps-placeholder:
  #   image: pelias/placeholder:master
  #   user: "${DOCKER_USER}"
  #   restart: always
  #   environment: ["PORT=4100"]
  #   ports: ["127.0.0.1:4100:4100"]
  #   volumes:
  #     - "./pelias.json:/code/pelias.json"
  #     - "${DATA_DIR}:/data"
  #     - "./blacklist/:/data/blacklist"

  # maps-whosonfirst:
  #   image: pelias/whosonfirst:master
  #   user: "${DOCKER_USER}"
  #   volumes:
  #     - "./pelias.json:/code/pelias.json"
  #     - "${DATA_DIR}:/data"

  # maps-elasticsearch:
  #   image: pelias/elasticsearch:7.17.27
  #   user: "${DOCKER_USER}"
  #   restart: always
  #   ports: ["127.0.0.1:9200:9200", "127.0.0.1:9300:9300"]
  #   volumes:
  #     - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
  #     - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add: ["IPC_LOCK"]
  #   security_opt:
  #     - seccomp=unconfined