# Complete help on configuration: https://dystroy.org/bacon/config/
# You may check the current default at
# https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.server]
command = ["cargo", "run", "--bin", "server"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]

[jobs.pull]
command = ["cargo", "run", "--bin", "pull"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]