apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-dispatcher
  template:
    metadata:
      labels:
        app: geography-dispatcher
    spec:
      initContainers:
        - name: wait-for-storage
          image: busybox:1.36
          envFrom:
            - configMapRef:
                name: geography-storage-config
          command:
            - sh
            - -c
            - |
              echo "Waiting for storage to be ready..."
              until wget -qO- $GEOGRAPHY_STORAGE_BASE_URL/minio/health/ready; do
                echo "Storage not ready yet..."
                sleep 2
              done
              echo "Storage ready, starting dispatcher..."
      containers:
        - name: geography-dispatcher
          image: geography-dispatcher:latest
          envFrom:
            - configMapRef:
                name: geography-storage-config
            - secretRef:
                name: geography-storage-credentials
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
