services:
  io:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=haydov
      - MINIO_ROOT_PASSWORD=haydov123
    volumes:
      - /tmp/haydov/geography:/data
    entrypoint: ["minio", "server", "--console-address", ":9001", "/data"]