services:
  osm-storage:
    build: ./storage
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    env_file:
      - .env
    volumes:
      - /tmp/haydov:/data