services:
  osm-dispatcher:
    build:
      context: ./dispatcher
      target: development
    env_file: .env
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./dispatcher
          target: /app
    ports:
      - 3000:3000

  osm-storage:
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-haydov_access}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-haydov_secret}
    labels:
      - "traefik.http.routers.haydov.rule=Host(`geography.haydov.localhost`)"
    develop:
      watch:
        - action: sync+exec
          path: ./storage
          target: /app
          exec:
            command: /bin/sh -c ./scripts/configure.sh