include:
  - ../routing/compose.yml
  - ../geocoding/compose.yml

services:
  maps:
    build: 
      context: ./
      target: production
    depends_on:
      - routing
      - geocoding
    ports:
      - 3000:3000