services:
  maps:
    tty: true
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/maps/src
    labels:
      - "traefik.http.routers.haydov.rule=Host(`maps.haydov.localhost`)"