apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haydov-maps

configMapGenerator:
  - name: config
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./k8s/namespace.yaml