apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haydov-maps

configMapGenerator:
  - name: osm-provider-plugin
    files:
      - ./plugin/config.yaml
      - ./target/wasm32-wasip2/release/data_provider.wasm

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./k8s/download-job.yaml