def build_maps_downloader():
  return docker_build(
    'maps-downloader',
    context='./',
    dockerfile='./Dockerfile',
    target='dev',
    build_args={'workspace_root': 'cargo-workspace'},
    live_update=[
        sync('./src', '/app/src'),
        run('cargo check', trigger=['./src/**/*.rs'])
    ]
  )