def install_maps_storage():
  map_storage = helm_resource(
      'maps-storage',
      'bitnami/minio',
      namespace='haydov', 
      flags=[
          '--version=17.0.12',
          '--values=./maps/services/storage/helm/values.yaml'
      ],
      port_forwards=[
          port_forward(9090, 9090, name='minio-console')
      ]
  )
  return map_storage