services:
  geography-dispatcher:
    build:
      context: ./dispatcher
      target: development
    ports:
      - 3000:3000
    env_file: .env
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./dispatcher
          target: /app

  geography-storage:
    build: ./storage
    depends_on:
      message:
        condition: service_healthy
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-haydov_test_access_key_id}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-haydov_test_secret_access_key}
      - MINIO_NOTIFY_AMQP_ENABLE_PRIMARY=${MINIO_NOTIFY_AMQP_ENABLE_PRIMARY:-on}
      - MINIO_NOTIFY_AMQP_URL_PRIMARY=${MINIO_NOTIFY_AMQP_URL_PRIMARY:-amqp://haydov_test_user:haydov_test_password@message:5672/}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_PRIMARY=${MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_PRIMARY:-fanout}
      - MINIO_NOTIFY_AMQP_EXCHANGE_PRIMARY=${MINIO_NOTIFY_AMQP_EXCHANGE_PRIMARY:-haydov.geography}
    labels:
      - "traefik.http.routers.haydov.rule=Host(`geography.haydov.localhost`)"
    volumes:
      - /tmp/haydov:/data
    develop:
      watch:
        - action: sync+exec
          path: ./storage
          target: /app
          exec:
            command: /bin/sh -c ./scripts/configure.sh
