apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maps-importer
  template:
    metadata:
      labels:
        app: maps-importer
    spec:
      initContainers:
        - name: wait-for-storage
          envFrom:
            - configMapRef:
                name: maps-storage-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for storage to be ready..."
              until wget -qO- $MAPS_STORAGE_BASE_URL/minio/health/ready; do
                echo "Storage not ready yet..."
                sleep 2
              done
              echo "Storage ready, starting dispatcher..."
      containers:
        - name: maps-importer
          image: maps-importer:latest
          envFrom:
            - configMapRef:
                name: maps-config
            - configMapRef:
                name: maps-storage-config
            - secretRef:
                name: maps-storage-credentials
            - configMapRef:
                name: message-broker-config
            - secretRef:
                name: message-broker-credentials
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
