apiVersion: v1
kind: ConfigMap
metadata:
  name: geography-storage-config
data:
  MINIO_API_PORT: "9000"
  MINIO_CONSOLE_PORT: "9001"
  MINIO_NOTIFY_AMQP_ENABLE_PRIMARY: "on"
  MINIO_NOTIFY_AMQP_EXCHANGE_PRIMARY: haydov.osm
  MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_PRIMARY: fanout
  MESSAGE_BROKER_ENDPOINT: message-broker:5672
