apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-storage
  template:
    metadata:
      labels:
        app: geography-storage
    spec:
      containers:
        - name: geography-storage
          image: geography-storage:latest
          envFrom:
            - configMapRef:
                name: geography-storage-config
            - configMapRef:
                name: geography-config
            - secretRef:
                name: message-broker-credentials
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: geography-credentials
                  key: STORAGE_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geography-credentials
                  key: STORAGE_SECRET_ACCESS_KEY
          ports:
            - containerPort: 9000 # API port
            - containerPort: 9001 # Admin port
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
