name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Get secrets from vault/AWS/etc
      run: |
        # Option A: Secrets from GitHub Secrets
        echo "MESSAGE_BROKER_USERNAME=prod_admin" >> $GITHUB_ENV
        echo "MESSAGE_BROKER_PASSWORD=${{ secrets.PROD_MESSAGE_BROKER_PASSWORD }}" >> $GITHUB_ENV
        
        # Option B: Pull from AWS Secrets Manager
        # aws secretsmanager get-secret-value --secret-id haydov/message-broker
        
        # Option C: Pull from HashiCorp Vault
        # vault kv get -field=password secret/haydov/message-broker
    
    - name: Generate kustomization with secrets
      run: |
        # Substitute environment variables in template
        envsubst < k8s/overlays/production/kustomization.template.yaml > k8s/overlays/production/kustomization.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k k8s/overlays/production
    
    - name: Cleanup (remove generated files)
      run: |
        rm k8s/overlays/production/kustomization.yaml